const courses = [
  {
    title: "JavaScript for Beginners",
    description:
      "Learn JavaScript from scratch and build interactive websites.",
    instructor: "John Doe",
    category: "development",
    level: "beginner",
    price: 49.99,
    duration: "6h 30m",
    image: "js-course.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 120,
    enrolledStudents: 300,
    published: true,
  },
  {
    title: "Advanced React.js",
    description: "Master React hooks, context API, and advanced patterns.",
    instructor: "Jane Smith",
    category: "development",
    level: "advanced",
    price: 69.99,
    duration: "8h 15m",
    image: "react-advanced.jpg",
    ratingsAverage: 4.7,
    ratingsQuantity: 220,
    enrolledStudents: 500,
    published: true,
  },
  {
    title: "UI/UX Design Fundamentals",
    description:
      "Learn the principles of user interface and experience design.",
    instructor: "Ali Mostafa",
    category: "design",
    level: "beginner",
    price: 39.99,
    duration: "4h 20m",
    image: "uiux.jpg",
    ratingsAverage: 4.3,
    ratingsQuantity: 90,
    enrolledStudents: 180,
    published: true,
  },
  {
    title: "Python for Data Science",
    description:
      "Data analysis, visualization, and machine learning using Python.",
    instructor: "Sara Youssef",
    category: "data",
    level: "intermediate",
    price: 59.99,
    duration: "10h 00m",
    image: "python-data.jpg",
    ratingsAverage: 4.6,
    ratingsQuantity: 150,
    enrolledStudents: 400,
    published: true,
  },
  {
    title: "Digital Marketing Mastery",
    description: "Grow your brand with proven marketing strategies.",
    instructor: "Mohamed El-Daly",
    category: "marketing",
    level: "intermediate",
    price: 45.0,
    duration: "7h 45m",
    image: "marketing.jpg",
    ratingsAverage: 4.4,
    ratingsQuantity: 130,
    enrolledStudents: 350,
    published: true,
  },
  {
    title: "Full Stack Web Development",
    description: "Become a full stack developer with MERN stack.",
    instructor: "Nourhan Hossam",
    category: "development",
    level: "advanced",
    price: 79.99,
    duration: "12h 00m",
    image: "fullstack.jpg",
    ratingsAverage: 4.8,
    ratingsQuantity: 300,
    enrolledStudents: 800,
    published: true,
  },
  {
    title: "Introduction to Cybersecurity",
    description:
      "Understand the basics of cybersecurity and how to stay protected.",
    instructor: "Kareem Abdelrahman",
    category: "other",
    level: "beginner",
    price: 29.99,
    duration: "3h 50m",
    image: "cyber.jpg",
    ratingsAverage: 4.2,
    ratingsQuantity: 70,
    enrolledStudents: 140,
    published: true,
  },
  {
    title: "SQL & Database Management",
    description: "Learn how to manage databases and write SQL queries.",
    instructor: "Dina Sherif",
    category: "data",
    level: "intermediate",
    price: 40.0,
    duration: "5h 30m",
    image: "sql.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 110,
    enrolledStudents: 210,
    published: true,
  },
  {
    title: "Graphic Design with Canva",
    description:
      "Create beautiful designs and social media graphics using Canva.",
    instructor: "Ahmed Galal",
    category: "design",
    level: "beginner",
    price: 25.0,
    duration: "3h 00m",
    image: "canva.jpg",
    ratingsAverage: 4.1,
    ratingsQuantity: 50,
    enrolledStudents: 100,
    published: true,
  },
  {
    title: "Node.js Crash Course",
    description: "Quickly learn how to build APIs using Node.js and Express.",
    instructor: "Yousef Elhesk",
    category: "development",
    level: "intermediate",
    price: 55.0,
    duration: "6h 00m",
    image: "node.jpg",
    ratingsAverage: 4.6,
    ratingsQuantity: 95,
    enrolledStudents: 220,
    published: true,
  },
  {
    title: "Social Media Marketing",
    description: "Grow your audience on Instagram, Facebook, and more.",
    instructor: "Mona Khaled",
    category: "marketing",
    level: "beginner",
    price: 30.0,
    duration: "4h 10m",
    image: "social-media.jpg",
    ratingsAverage: 4.3,
    ratingsQuantity: 80,
    enrolledStudents: 190,
    published: true,
  },
  {
    title: "Responsive Web Design",
    description:
      "Build responsive websites using HTML, CSS, and media queries.",
    instructor: "Hassan Fathi",
    category: "design",
    level: "intermediate",
    price: 35.0,
    duration: "4h 40m",
    image: "responsive.jpg",
    ratingsAverage: 4.4,
    ratingsQuantity: 60,
    enrolledStudents: 150,
    published: true,
  },
  {
    title: "Data Structures in JavaScript",
    description: "Master arrays, stacks, queues, linked lists, and more.",
    instructor: "Tarek Salem",
    category: "development",
    level: "advanced",
    price: 49.0,
    duration: "5h 30m",
    image: "ds.jpg",
    ratingsAverage: 4.7,
    ratingsQuantity: 100,
    enrolledStudents: 250,
    published: true,
  },
  {
    title: "Time Management for Students",
    description: "Learn how to organize your study time and stay productive.",
    instructor: "Esraa Gamal",
    category: "other",
    level: "beginner",
    price: 20.0,
    duration: "2h 20m",
    image: "time.jpg",
    ratingsAverage: 4.0,
    ratingsQuantity: 45,
    enrolledStudents: 90,
    published: true,
  },
  {
    title: "Machine Learning Essentials",
    description: "Understand the basics of ML and build simple models.",
    instructor: "Ramy Adel",
    category: "data",
    level: "advanced",
    price: 70.0,
    duration: "9h 00m",
    image: "ml.jpg",
    ratingsAverage: 4.6,
    ratingsQuantity: 140,
    enrolledStudents: 310,
    published: true,
  },
];

export default courses;
